version: '3'

services:
  database:
    container_name: database
    restart: always
    image: mongo:latest
    volumes:
      - db-data:/data/db

  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/opt/project/api
    expose:
      - 5000
    env_file:
      - development.env
    depends_on:
      - database
      - mailserver
    command: uvicorn main:app --log-level="debug" --debug --workers=4 --http h11 --host="0.0.0.0" --port=5000 --root-path="/api" --timeout-keep-alive=3600

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - frontend
    volumes:
      - ./api/public:/opt/project/api/public
      - ./docker/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    expose:
      - 3000
    depends_on:
      - api
    volumes:
      - ./frontend:/opt/frontend
    env_file:
      - development.env
    working_dir: /opt/frontend
    command: sh -c "yarn install && yarn dev"

  mailserver:
    container_name: mailserver
    image: oanhnn/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: certonly  --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com  -d www.example.com
volumes:
  db-data:
    driver: local
