from enum import Enum


class Rank(str, Enum):
    PRIVATE = "GF1"
    PRIVATE_FIRST_CLASS = "GF2"
    JUNIOR_SERGEANT = "GF3"
    SERGEANT = "GF4"
    SENIOR_SERGEANT = "GF5"
    FIRST_SERGEANT = "GF6"
    WARRANT_OFFICER = "GF7"
    CHIEF_WARRANT_OFFICER = "GF8"
    JUNIOR_LIEUTENANT = "GF9"
    LIEUTENANT = "GF10"
    SENIOR_LIEUTENANT = "GF11"
    CAPTAIN = "GF12"
    MAJOR = "GF13"
    LIEUTENANT_COLONEL = "GF14"
    COLONEL = "GF15"
    MAJOR_GENERAL = "GF16"
    LIEUTENANT_GENERAL = "GF17"
    COLONEL_GENERAL = "GF18"
    ARMY_GENERAL = "GF19"
    MARSHAL = "GF20"
